name: Destroy with Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan-with-terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'
      
      - name: Terraform format
        run: terraform fmt -check
        working-directory: terraform/
   
      - name: Terraform init
        run: terraform init -backend-config="bucket=${{ secrets.TF_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
        working-directory: terraform/
      
      - name: Terraform validate
        run: terraform validate -no-color
        working-directory: terraform/

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform/
   
